### ISSUE TITLE
top bar height (was: Change font of the time)

### ISSUE THREAD

**Issue by ZeroBit** [UnnamedHero/pebble-watchface-time-and-calendar#1]
It is the excellent app. I love it. Thank you for developing!
1) Please, give the ability to change the font of the time. I wanted to make it bigger or/and bold. It is possible id reduce the battery icon and to put it horizontally.  
2) Also is it possible to change the size of inactive days in the calendar? The one is active today's date should be as it is now. But all others size can be a bit reduced.
3) Can I completely switch off the second screen weather forecast? Sometimes I want to switch on the light to see current time, but I see weather forecast instead. And I need to wait until it is switched back or to switch it manually with shaking again what is not convenient (especially when it is night and every additional shake can wake up my wife)
Thank you for developing!!!

**Comment by UnnamedHero** [comment]
Thank you for a feedback.
1. Time font is already bold. But I can make it a little bit bigger. It is maximum size for this font, I think. Look here:
old: ![pebble_screenshot_2017-09-14_23-29-55](https://user-images.githubusercontent.com/1024934/30454764-1ecb13f2-99a6-11e7-8db0-71a70a18d945.png) new: ![pebble_screenshot_2017-09-14_23-44-25](https://user-images.githubusercontent.com/1024934/30454768-233a1dfc-99a6-11e7-839a-7ccb9b4802a1.png)
2. Like this? 
![pebble_screenshot_2017-09-15_00-02-51](https://user-images.githubusercontent.com/1024934/30455448-a3eddee6-99a8-11e7-8a65-c40e011021f4.png) or ![pebble_screenshot_2017-09-15_00-11-55](https://user-images.githubusercontent.com/1024934/30455776-ce382854-99a9-11e7-8aa4-f860849dbd3c.png)


3. It is possible. I'll make a option for it next version. I'm using left button to turn on the backlight at this moment, and completely switch off backlight by shake.

**Comment by ZeroBit** [comment]
Thank you for your hard work!
1. The new is better. I mean to put even more higher to have some equal space calendar and date. Please, take a look here (I shifted it up)
![watchface_new](https://user-images.githubusercontent.com/6258813/30483800-e3ab72d6-9a30-11e7-97a8-1da07777edee.png)
2. The 1st picture is clean and neat. It is very beautiful. But I suppose for people with poor sight the second variant is more preferable. 
3. Thank you. The possibility of switching off the weather forecast is more preferable for me. When I run to the transport I couldn't see time because of the weather forecast.
4. Can you make upper line more narrow putting battery in horizontal position?
5. Can you support weather forecast for a official Pebble app alternative which is smaller and opensource - https://gadgetbridge.org/ ? Here is the github for it https://github.com/Freeyourgadget/Gadgetbridge  . It uses API for a weather https://github.com/Freeyourgadget/Gadgetbridge/issues/528 
[Here](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-System-Apps) is written 

> Starting with version 0.17, Gadgetbridge offers support for weather information on your Pebble. To do this without requiring the INTERNET permission for itself, this requires the help of a weather provider on your Android device – which is provided by the Weather notification app available at F-Droid. 

Thank you, Thank you very much for developing the best watchface for Pebble!!!

**Comment by UnnamedHero** [comment]
Let's split this issue into separate independent tasks.
Time font size moved to #2 
Calendar's font sizes to #3 
Gadgetbridge support to #4 
Forecast window #5

This issue will describe top bar height

**Comment by UnnamedHero** [comment]
So.... about top line. It's only 20 pixel height. I'm planning to add there some indication. For  example:
 - Weather API key problems;
 - Quiet time indication;
 - ....
20 pixels is minimum size, that allow small pics looks more or less acceptable, not ugly.
