### ISSUE TITLE
Vibro on watchface appearance switch off option

### ISSUE THREAD

**Issue by ZeroBit** [UnnamedHero/pebble-watchface-time-and-calendar#10]
After each call when the watchface appears after any other screen it makes vibro. When I go to Settings and back it makes vibro. It irritates a bit. Probably for other people it is OK. But not for me. I like vibro only when something important happens.  Is it possible to make vibro when the watchface appears optional (add an option to switch it off in the settings menu)?

**Comment by UnnamedHero** [comment]
What version do you have? I've just fixed something like this in 0.32. 0.33 is in Pebble Store now.

**Comment by ZeroBit** [comment]
I use version from Google Drive you shared with me

**Comment by UnnamedHero** [comment]
Oh... I think it is the last version having this issue. Please update to last version from pebble store.

**Comment by ZeroBit** [comment]
Yes, The latest version is without this disturbing vibro. Thank you
