### ISSUE TITLE
Make time font bigger

### ISSUE THREAD

**Issue by UnnamedHero** [UnnamedHero/pebble-watchface-time-and-calendar#2]
@ZeroBit: Please, give the ability to change the font of the time. I wanted to make it bigger or/and bold. It is possible id reduce the battery icon and to put it horizontally.

**Comment by UnnamedHero** [comment]
fixed in 0.30.0 [download dev version](https://drive.google.com/open?id=0B9g5sjcPqSJfbkc4UFR1RlJKZkk)

**Comment by ZeroBit** [comment]
Thank you. Now it looks much, much better.
