### ISSUE TITLE
"Time and Calend is not responding" error

### ISSUE THREAD

**Issue by ZeroBit** [UnnamedHero/pebble-watchface-time-and-calendar#6]
The latest dev version 0.30 after some time gives error "Time and Calend is not resonding"
Probably it is because I use gadgetbridge app...

![img_20170916_155635](https://user-images.githubusercontent.com/6258813/30512412-c7c43036-9af7-11e7-8420-4eb31fb63516.jpg)

**Comment by ZeroBit** [comment]
After some time of using this app I have this error. 
![img_20170916_161523](https://user-images.githubusercontent.com/6258813/30512546-90484ba8-9afa-11e7-99c9-a442bcd7b523.jpg)


I will install the official Pebble app to restore firmware.

**Comment by UnnamedHero** [comment]
This is because of gadgetbridge application. At this moment only official Pebble app is supported.
Waiting for #4

**Comment by ZeroBit** [comment]
Unfortunately even with official app today in the morning I found my Pebble switched off with a black screen. After I switched the smartwatch on I found this picture
![img_20170918_113552_problem](https://user-images.githubusercontent.com/6258813/30534697-045a7f02-9c68-11e7-85d0-3cdded5170f0.jpg)
Usually I take the phone during my sleep with me in the different room. But the watch I leave in the kitchen. My Telephone loses connection with my watch. And then the watch does to the "Stand-By Mode", which is ON on my watch. So the problem, I suppose, appear when a watchface loses connection with a phone.
Please, fix it

**Comment by UnnamedHero** [comment]
I have the same issue, after installing gadgetbridge. And after disabling gadgetbridge and reinstalling firmware with official app, I've got firmware error again after some time with official app. After reinstalling firmware again, everything is OK. I think this is because of gadgetbridge.

**Comment by ZeroBit** [comment]
I reinstalled firmware again today in the morning with official app second time. (I already deleted GadgetBridge). Let's see..

**Comment by ZeroBit** [comment]
Again the same problem in the morning. Black screen. 
![black](https://user-images.githubusercontent.com/6258813/30579977-9fc56c48-9d23-11e7-8f37-90ec5e156adc.jpg)

Then, when I powered on the watch I can see SOS screen 

![sos](https://user-images.githubusercontent.com/6258813/30579990-a81c3aca-9d23-11e7-9d18-1a985b5fa647.png)

**Comment by UnnamedHero** [comment]
Same thing today's morning. I think the "killer is" gadgetbridge, because after restoring firmware with official app all watchface's data was loaded (API key for example). I'll continue my examination of this process. Still do not now what cause the problem

**Comment by ZeroBit** [comment]
Today I left the watch with another watchface active for a night. In the morning everything is OK. The problem of SOS screen arises only with TaC watchface. I am sure that the watch is going to SOS screen after 1) connection with a phone is lost and 2) watchface tries to get to know the weather. If you check (before the weather checking) the status of connection with a phone and then avoid the weather retrieving it will be the solution.

**Comment by UnnamedHero** [comment]
Bluetooth connection status is checking before sending message [here](https://github.com/UnnamedHero/pebble-watchface-time-and-calendar/blob/0212fa723213ebfdff94fa73bce58cabbbb958f9/src/c/utils/messagesystem.c#L96l)

**Comment by ZeroBit** [comment]
I hace made a small video which shows how the SOS problem appears in 7 minutes after bluetooth disconnection.
You can download or watch it [here](https://my.pcloud.com/publink/show?code=XZXiT77ZXMiCjL2YRjL9hpvR0a2l3LY4zIUX) 
Please, also what happens at time 2:42.

**Comment by UnnamedHero** [comment]
Thanks you for the video and feedback.
I have a couple ideas what can cause it.

**Comment by UnnamedHero** [comment]
@ZeroBit , can you please test new version[from google drive](https://drive.google.com/open?id=0B9g5sjcPqSJfOVR0NHc4Nnl1ZFE) ?

**Comment by ZeroBit** [comment]
Thank you for working hard to make the most functional and convenient watchface of all!!!
I just downloaded your latest version and uploaded it to the watch. Lets see...

**Comment by ZeroBit** [comment]
I left for two hours without bluetooth. Everything is OK. It seems you have solved the problem!

**Comment by ZeroBit** [comment]
After all night there is no any problem. Thank you very, very much for solving the issue!!!
