### ISSUE TITLE
иконка T-a-C не отображается при наведении в списке циферблатов

### ISSUE THREAD

**Issue by UnnamedHero** [UnnamedHero/pebble-watchface-time-and-calendar#8]
надо разобраться.
иконка T-a-C не отображается при наведении в списке циферблатов

**Comment by ZeroBit** [comment]
У меня все нормально отображается... 
![img_20170918_145821](https://user-images.githubusercontent.com/6258813/30541160-d1beea2c-9c82-11e7-84f8-c82a490f7f3f.jpg)

Но в самом приложении Pebble - нет. Но это нормально, если приложение без подписи. (Huawei Mate 8, Android 7.0) 

![screenshot_20170918-150129](https://user-images.githubusercontent.com/6258813/30541162-d784fd7a-9c82-11e7-81c3-8260b79700e4.png)

**Comment by UnnamedHero** [comment]
Проблема наблюдается на чёрно-белом экране. Во всяком случае, на моих pebble classic так было изначально, но я тогда был занят реализацией основных функций циферблата и совершенно забыл про это. А вот в закладке watchface в приложении pebble я иконку не делал ещё. Например, у того же timely у меня иконка отображается.

**Comment by ZeroBit** [comment]
У меня в Timely иконка перестала изображаться с тех пор, как я вручную модифицировал watchface, изменив appid для openweather, чтобы у меня отображалась погода. Как я понял, не отображаются значки неподписанных watchfaceов. У меня не получилось переподвисать Timely, поэтому у меня значок там не отображается... Но это меня не волнует. Лучше с погодой, но без значка, чем со оригинальным значком, но без погоды.

**Comment by ZeroBit** [comment]
Сегодня утром опять черный экран на часах. Включил, экран SOS. Сейчас опять восстанавливаю из аварийного режима, как и вчера утром...

**Comment by UnnamedHero** [comment]
А чего стесняться. У меня тоже вчера прошивка слетела. Но чего-то мне слабо верится, что это из-за циферблата. Мне кажется, это наследие gadgetbridge, так как после восстановления прошивки данные (тот же API ключ) остались. Продолжаю наблюдение. Пока не выявил закономерности.

**Comment by UnnamedHero** [comment]
fixed
