### ISSUE TITLE
Feature request: Alarm info on the top

### ISSUE THREAD

**Issue by ZeroBit** [UnnamedHero/pebble-watchface-time-and-calendar#9]
Is it possible to display if the alarm is set on the top of the display? If it is is it possible to display the type of the alarm: is it the smart alarm or usual?
There are many variants [here](https://icons8.com/icon/42214/alarm-clock)

**Comment by UnnamedHero** [comment]
I'm afraid it is not possible. I can't find any API for it. If you know any working example - let me know.
